### PR TITLE
add dot-env-file

### PR DESCRIPTION
**Pull request by akssshh**

### CODE REVIEW

**Comment by Haimantika** [comment]
> _ No description provided. _

Have you tested the code with your API keys? This won’t work, we need to write the server-side code.

**Comment by akssshh** [comment]
> > _ No description provided. _
> 
> Have you tested the code with your API keys? This won’t work, we need to write the server-side code.

Yeah, this will not work. Server side code is required to run env variables. Also after replacing with my own API key, it's showing Error generating text.

**Comment by prithweedas** [comment]
@akssshh As this is hosted on vercel, might be a good idea to take a look at [vercel serverless functions](https://vercel.com/docs/functions/serverless-functions) to proxy requests to OpenAI.
This way API key won't get exposed to client devices.

**Comment by akssshh** [comment]
> @akssshh As this is hosted on vercel, might be a good idea to take a look at [vercel serverless functions](https://vercel.com/docs/functions/serverless-functions) to proxy requests to OpenAI. This way API key won't get exposed to client devices.

Yeah. This will work but configuration has to be done on the deployment page.

**Comment by Haimantika** [comment]
> @akssshh As this is hosted on vercel, might be a good idea to take a look at [vercel serverless functions](https://vercel.com/docs/functions/serverless-functions) to proxy requests to OpenAI. This way API key won't get exposed to client devices.

This is a good suggestion. Thanks @prithweedas . 
@akssshh do you want me to write the solution for it? Or do you want to write the server-side code?

**Pull request closed without merging**
